version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/lambda/media_uploads"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    open-pull-requests-limit: 0
