name: "Terraform CD (Apply)"

on:
  push:
    branches:
      - main
    paths:
      - 'envs/**'
      - 'modules/**'

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.14.3"

concurrency:
  group: terraform-cd
  cancel-in-progress: false

jobs:
  deploy-dev:
    uses: ./.github/workflows/reusable-terraform-deploy.yml
    with:
      env_name: dev
      tf_working_dir: infra/envs/dev
      aws_region: ap-northeast-1
      role_plan: arn:aws:iam::<ACCOUNT_ID>:role/gh-terraform-plan-dev
      role_apply: arn:aws:iam::<ACCOUNT_ID>:role/gh-terraform-apply-dev

  deploy-prod:
    needs: deploy-dev
    uses: ./.github/workflows/reusable-terraform-deploy.yml
    with:
      env_name: prod
      tf_working_dir: infra/envs/prod
      aws_region: ap-northeast-1
      role_plan: arn:aws:iam::<ACCOUNT_ID>:role/gh-terraform-plan-prod
      role_apply: arn:aws:iam::<ACCOUNT_ID>:role/gh-terraform-apply-prod
      environment_name: production
